name: "HASSIO Gateway"
description: "Add gateway to Home Assistant"
version: "1.0.1"
slug: "hassio_gateway"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8000/tcp: 8000